Repository rsocket/rsocket-java, pull requests merged in 2020-10, with the labels that each got.

#941 Safer iteration when cancelling subscriptions
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
Labels: bug

#945 use heap buffers in the default payload decoder
  rsocket-core/src/main/java/io/rsocket/frame/decoder/DefaultPayloadDecoder.java
Labels: enhancement

#944 provides request intercepting api
  rsocket-core/build.gradle
  rsocket-core/src/main/java/io/rsocket/core/FireAndForgetRequesterMono.java
  rsocket-core/src/main/java/io/rsocket/core/FireAndForgetResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/core/RequestChannelRequesterFlux.java
  rsocket-core/src/main/java/io/rsocket/core/RequestChannelResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RequestResponseRequesterMono.java
  rsocket-core/src/main/java/io/rsocket/core/RequestResponseResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RequestStreamRequesterFlux.java
  rsocket-core/src/main/java/io/rsocket/core/RequestStreamResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RequesterResponderSupport.java
  rsocket-core/src/main/java/io/rsocket/plugins/CompositeRequestInterceptor.java
  rsocket-core/src/main/java/io/rsocket/plugins/InitializingInterceptorRegistry.java
  rsocket-core/src/main/java/io/rsocket/plugins/InterceptorRegistry.java
  rsocket-core/src/main/java/io/rsocket/plugins/RequestInterceptor.java
  rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java
  rsocket-core/src/test/java/io/rsocket/core/FireAndForgetRequesterMonoTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/RequestChannelResponderSubscriberTest.java
  rsocket-core/src/test/java/io/rsocket/core/RequesterOperatorsRacingTest.java
  rsocket-core/src/test/java/io/rsocket/core/ResponderOperatorsCommonTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
  rsocket-core/src/test/java/io/rsocket/core/TestRequesterResponderSupport.java
  rsocket-core/src/test/java/io/rsocket/plugins/RequestInterceptorTest.java
  rsocket-core/src/test/java/io/rsocket/plugins/TestRequestInterceptor.java
Labels: enhancement

#949 Update WeightedLoadbalanceStrategy to use a Builder
  rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceRSocketClient.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java
Labels: enhancement

#950 Rename RequestInterceptor registration methods
  rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java
  rsocket-core/src/main/java/io/rsocket/plugins/InitializingInterceptorRegistry.java
  rsocket-core/src/main/java/io/rsocket/plugins/InterceptorRegistry.java
  rsocket-core/src/test/java/io/rsocket/plugins/RequestInterceptorTest.java
Labels: task
