Repository rsocket/rsocket-java, pull requests merged in 2020-08, with the labels that each got.

#904 Reject any frames before SETUP/LEASE
  rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketServerTest.java
  rsocket-core/src/test/java/io/rsocket/internal/ClientServerInputMultiplexerTest.java
Labels: enhancement

#903 Reject empty fragments
  rsocket-core/src/main/java/io/rsocket/fragmentation/FrameReassembler.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FrameReassemblerTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/ReassembleDuplexConnectionTest.java
Labels: enhancement

#908 provides tests for maxInboundPayloadSize check and related fixes
  rsocket-core/src/main/java/io/rsocket/core/FireAndForgetResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/FragmentationUtils.java
  rsocket-core/src/main/java/io/rsocket/core/ReassemblyUtils.java
  rsocket-core/src/main/java/io/rsocket/core/RequestChannelResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RequestResponseResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RequestStreamResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/SendUtils.java
  rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java
  rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/TestRequesterResponderSupport.java
  rsocket-core/src/test/java/io/rsocket/test/util/TestDuplexConnection.java
Labels: task

#906 removes deprecations dedicated for 1.1
  benchmarks/src/main/java/io/rsocket/core/RSocketPerf.java
  rsocket-core/src/main/java/io/rsocket/AbstractRSocket.java
  rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/ResponderRSocket.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/exceptions/ApplicationErrorException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/CanceledException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/ConnectionCloseException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/ConnectionErrorException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/CustomRSocketException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/InvalidException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/RSocketException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/RejectedException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/RejectedResumeException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/SetupException.java
  rsocket-core/src/main/java/io/rsocket/keepalive/KeepAliveSupport.java
  rsocket-core/src/main/java/io/rsocket/metadata/CompositeMetadata.java
  rsocket-core/src/main/java/io/rsocket/metadata/CompositeMetadataFlyweight.java
  rsocket-core/src/main/java/io/rsocket/metadata/TaggingMetadataFlyweight.java
  rsocket-core/src/main/java/io/rsocket/metadata/security/AuthMetadataFlyweight.java
  rsocket-core/src/main/java/io/rsocket/metadata/security/WellKnownAuthType.java
  rsocket-core/src/main/java/io/rsocket/resume/ExponentialBackoffResumeStrategy.java
  rsocket-core/src/main/java/io/rsocket/resume/PeriodicResumeStrategy.java
  rsocket-core/src/main/java/io/rsocket/resume/ResumeStrategy.java
  rsocket-core/src/main/java/io/rsocket/transport/TransportHeaderAware.java
  rsocket-core/src/test/java/io/rsocket/exceptions/RSocketExceptionTest.java
  rsocket-core/src/test/java/io/rsocket/exceptions/TestRSocketException.java
  rsocket-core/src/test/java/io/rsocket/metadata/AuthMetadataCodecTest.java
  rsocket-core/src/test/java/io/rsocket/metadata/CompositeMetadataCodecTest.java
  rsocket-core/src/test/java/io/rsocket/metadata/CompositeMetadataTest.java
  rsocket-core/src/test/java/io/rsocket/metadata/TaggingMetadataTest.java
  rsocket-core/src/test/java/io/rsocket/resume/ResumeExpBackoffTest.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/client/WebsocketClientTransportTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketServerTransportTest.java
Labels: breaking changes, for user attention, task

#913 Reject frames less than min MTU size
  rsocket-core/src/main/java/io/rsocket/core/FireAndForgetResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/ReassemblyUtils.java
  rsocket-core/src/main/java/io/rsocket/core/RequestChannelResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RequestResponseResponderSubscriber.java
  rsocket-core/src/main/java/io/rsocket/core/RequestStreamResponderSubscriber.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
Labels: enhancement

#922 makes part of the API package-private
  rsocket-core/src/main/java/io/rsocket/loadbalance/Ewma.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/FrugalQuantile.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceRSocketClient.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceStrategy.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/Median.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/Quantile.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/RSocketPool.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/RoundRobinLoadbalanceStrategy.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/Stats.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedLoadbalanceStrategy.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/WeightedRSocket.java
  rsocket-core/src/main/java/io/rsocket/loadbalance/stat/Quantile.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/loadbalancer/RoundRobinRSocketLoadbalancerExample.java
  rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java
Labels: enhancement
