Repository rsocket/rsocket-java, pull requests merged in 2020-06, with the labels that each got.

#854 fixes ConnectionSetupPayload refcnt management
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketConnectorTest.java
Labels: bug

#856 RSocketClient and RSocketConnector Javadoc update
  rsocket-core/src/main/java/io/rsocket/RSocketClient.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
Labels: documentation

#855 ensures lease is used exactly on request frame sending
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
Labels: task

#861 fixes responder to handle errors according to the spec
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
Labels: bug

#863 provides error handling in case Bubbling / NIC exceptions
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
Labels: bug

#868 provides an example of peer to peer communication
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/fnf/TaskProcessingWithServerSideNotificationsExample.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/lease/LeaseExample.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/ClientStreamingToServer.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/ServerStreamingToClient.java
Labels: documentation
