Repository rsocket/rsocket-java, pull requests merged in 2020-04, with the labels that each got.

#770 Reduce top-level package dependencies
  rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultClientRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultConnectionSetupPayload.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultServerRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/core/ReconnectMono.java
  rsocket-core/src/main/java/io/rsocket/core/StreamIdSupplier.java
  rsocket-core/src/main/java/io/rsocket/core/package-info.java
  rsocket-core/src/main/java/io/rsocket/plugins/SocketAcceptorInterceptor.java
  rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java
  rsocket-core/src/test/java/io/rsocket/core/ConnectionSetupPayloadTest.java
  rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTerminationTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/ReconnectMonoTests.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
  rsocket-core/src/test/java/io/rsocket/core/StreamIdSupplierTest.java
  rsocket-core/src/test/java/io/rsocket/core/TestingStuff.java
Labels: refactorings

#736 [Bugfix] Incorrect Behaviour of RequestChannel
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/frame/FrameUtil.java
  rsocket-core/src/main/java/io/rsocket/internal/RateLimitableRequestPublisher.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/internal/RateLimitableRequestPublisherTest.java
  rsocket-test/src/main/java/io/rsocket/test/TestRSocket.java
  rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
Labels: bug, enhancement

#768 Payload length validation
  rsocket-core/src/main/java/io/rsocket/core/DefaultClientRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultServerRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/PayloadValidationUtils.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FrameFragmenter.java
  rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java
  rsocket-core/src/test/java/io/rsocket/core/PayloadValidationUtilsTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
Labels: bug

#774 reduce package cycles
  rsocket-core/src/main/java/io/rsocket/RSocketErrorException.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultClientRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultServerRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java
  rsocket-core/src/main/java/io/rsocket/exceptions/ApplicationErrorException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/CanceledException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/ConnectionCloseException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/ConnectionErrorException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/CustomRSocketException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/Exceptions.java
  rsocket-core/src/main/java/io/rsocket/exceptions/InvalidException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/InvalidSetupException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/RSocketException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/RejectedException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/RejectedResumeException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/RejectedSetupException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/SetupException.java
  rsocket-core/src/main/java/io/rsocket/exceptions/UnsupportedSetupException.java
  rsocket-core/src/main/java/io/rsocket/frame/ErrorFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/ErrorType.java
  rsocket-core/src/main/java/io/rsocket/internal/ClientSetup.java
  rsocket-core/src/main/java/io/rsocket/lease/MissingLeaseException.java
  rsocket-core/src/main/java/io/rsocket/lease/RequesterLeaseHandler.java
  rsocket-core/src/main/java/io/rsocket/lease/ResponderLeaseHandler.java
  rsocket-core/src/main/java/io/rsocket/util/ConnectionUtils.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/exceptions/RSocketExceptionTest.java
Labels: refactorings

#780 RSocketFactory API enhancements
  README.md
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultClientRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultServerRSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/core/Resume.java
  rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java
  rsocket-core/src/main/java/io/rsocket/plugins/InitializingInterceptorRegistry.java
  rsocket-core/src/main/java/io/rsocket/plugins/InterceptorRegistry.java
  rsocket-core/src/main/java/io/rsocket/plugins/PluginRegistry.java
  rsocket-core/src/main/java/io/rsocket/plugins/Plugins.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketServerFragmentationTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
  rsocket-core/src/test/java/io/rsocket/internal/ClientServerInputMultiplexerTest.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/channel/ChannelEchoClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/duplex/DuplexClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/lease/LeaseExample.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/requestresponse/HelloWorldClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/StreamingClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketHeadersSample.java
  rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java
  rsocket-examples/src/test/java/io/rsocket/integration/InteractionsLoadTest.java
  rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java
  rsocket-examples/src/test/java/io/rsocket/integration/TestingStreaming.java
  rsocket-examples/src/test/java/io/rsocket/resume/ResumeIntegrationTest.java
  rsocket-test/src/main/java/io/rsocket/test/ClientSetupRule.java
  rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
  rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalPingPong.java
  rsocket-transport-netty/src/test/java/io/rsocket/integration/FragmentTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/RSocketFactoryNettyTransportFragmentationTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/SetupRejectionTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpPing.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpPongServer.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebSocketTransportIntegrationTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketPing.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketPingPongIntegrationTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketPongServer.java
Labels: new API

#775 [Bugfix] Enforces reassembly to always be enabled
  rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FrameFragmenter.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FrameReassembler.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/ReassemblyDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/package-info.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/ReassembleDuplexConnectionTest.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketHeadersSample.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalServerTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
  rsocket-transport-netty/src/test/java/io/rsocket/integration/FragmentTest.java
Labels: bug

#784 Follow-up fix for commit 0ac54d4b
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
Labels: bug

#785 Restore ConnectionSetupPayload as abstract class
  rsocket-core/src/main/java/io/rsocket/ConnectionSetupPayload.java
  rsocket-core/src/main/java/io/rsocket/core/DefaultConnectionSetupPayload.java
Labels: bug

#777 Track Discarded Payloads
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/util/CharByteBufUtil.java
  rsocket-core/src/test/java/io/rsocket/buffer/LeaksTrackingByteBufAllocator.java
  rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/frame/ByteBufRepresentation.java
Labels: bug

#794 fixes requestChannel and ensure support of half-closed state
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
Labels: bug

#795 Drop UriHandler and UriTransportRegistry
  rsocket-core/src/main/java/io/rsocket/uri/UriHandler.java
  rsocket-core/src/main/java/io/rsocket/uri/UriTransportRegistry.java
  rsocket-core/src/test/java/io/rsocket/uri/TestUriHandler.java
  rsocket-core/src/test/java/io/rsocket/uri/UriTransportRegistryTest.java
  rsocket-core/src/test/resources/META-INF/services/io.rsocket.uri.UriHandler
  rsocket-test/src/main/java/io/rsocket/test/UriHandlerTest.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalUriHandler.java
  rsocket-transport-local/src/main/resources/META-INF/services/io.rsocket.uri.UriHandler
  rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalUriHandlerTest.java
  rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalUriTransportRegistryTest.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpUriHandler.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketUriHandler.java
  rsocket-transport-netty/src/main/resources/META-INF/services/io.rsocket.uri.UriHandler
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpUriHandlerTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/TcpUriTransportRegistryTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketUriHandlerTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketUriTransportRegistryTest.java
Labels: task

#783 Fixes Payload#hasMetadata to strictly flow the flag in frame
  rsocket-core/src/main/java/io/rsocket/core/DefaultConnectionSetupPayload.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FrameReassembler.java
  rsocket-core/src/main/java/io/rsocket/frame/DataAndMetadataFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/ExtensionFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/FragmentationFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/KeepAliveFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/LeaseFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/MetadataPushFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/PayloadFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestChannelFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestFireAndForgetFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestNFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestResponseFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestStreamFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/SetupFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/decoder/DefaultPayloadDecoder.java
  rsocket-core/src/main/java/io/rsocket/frame/decoder/ZeroCopyPayloadDecoder.java
  rsocket-core/src/main/java/io/rsocket/util/ByteBufPayload.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationIntegrationTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FrameFragmenterTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FrameReassemblerTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/ReassembleDuplexConnectionTest.java
  rsocket-core/src/test/java/io/rsocket/frame/DataAndMetadataFlyweightTest.java
  rsocket-core/src/test/java/io/rsocket/frame/ExtensionFrameFlyweightTest.java
  rsocket-core/src/test/java/io/rsocket/frame/PayloadFlyweightTest.java
  rsocket-core/src/test/java/io/rsocket/frame/RequestFlyweightTest.java
  rsocket-core/src/test/java/io/rsocket/util/ByteBufPayloadTest.java
  rsocket-core/src/test/java/io/rsocket/util/DefaultPayloadTest.java
  rsocket-test/src/main/java/io/rsocket/test/TestFrames.java
  rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
Labels: bug, enhancement

#796 Refactors how `ByteBufAllocator` is used and setup
  rsocket-core/src/main/java/io/rsocket/DuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/ReassemblyDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java
  rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java
  rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/resume/ServerRSocketSession.java
  rsocket-core/src/main/java/io/rsocket/util/DuplexConnectionProxy.java
  rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java
  rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/ReassembleDuplexConnectionTest.java
  rsocket-core/src/test/java/io/rsocket/internal/ClientServerInputMultiplexerTest.java
  rsocket-core/src/test/java/io/rsocket/test/util/LocalDuplexConnection.java
  rsocket-core/src/test/java/io/rsocket/test/util/TestClientTransport.java
  rsocket-core/src/test/java/io/rsocket/test/util/TestDuplexConnection.java
  rsocket-core/src/test/java/io/rsocket/test/util/TestServerTransport.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketHeadersSample.java
  rsocket-micrometer/src/main/java/io/rsocket/micrometer/MicrometerDuplexConnection.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalServerTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
Labels: enhancement

#798 Deprecate ResumeStrategy and replace with Reactor Retry
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/Resume.java
  rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java
  rsocket-core/src/main/java/io/rsocket/resume/ExponentialBackoffResumeStrategy.java
  rsocket-core/src/main/java/io/rsocket/resume/PeriodicResumeStrategy.java
  rsocket-core/src/main/java/io/rsocket/resume/ResumeStrategy.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java
  rsocket-examples/src/test/java/io/rsocket/resume/ResumeIntegrationTest.java
Labels: enhancement

#799 Fixes possible elements' leaks occurrence
  rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java
  rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java
Labels: bug

#800 Fix logging in examples and load-balancer tests
  rsocket-examples/build.gradle
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/channel/ChannelEchoClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/requestresponse/HelloWorldClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/Files.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/StreamingClient.java
  rsocket-examples/src/main/resources/log4j.properties
  rsocket-examples/src/main/resources/logback.xml
  rsocket-examples/src/test/resources/log4j.properties
  rsocket-examples/src/test/resources/logback-test.xml
  rsocket-load-balancer/build.gradle
  rsocket-load-balancer/src/test/resources/log4j.properties
  rsocket-load-balancer/src/test/resources/logback-test.xml
Labels: task

#801 Default errorConsumer to no-op in the new API
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
Labels: task

#803 provides more `ByteBuf` leaks fixes
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/frame/DataAndMetadataFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/LeaseFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/MetadataPushFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/PayloadFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestChannelFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestFireAndForgetFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestResponseFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/frame/RequestStreamFrameFlyweight.java
  rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoProcessor.java
  rsocket-core/src/test/java/io/rsocket/buffer/LeaksTrackingByteBufAllocator.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/frame/ByteBufRepresentation.java
Labels: bug

#802 Deprecate ResponderRSocket
  rsocket-core/src/main/java/io/rsocket/ResponderRSocket.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
Labels: refactorings

#804 Removes TupleByteBufs
  rsocket-core/src/main/java/io/rsocket/buffer/AbstractTupleByteBuf.java
  rsocket-core/src/main/java/io/rsocket/buffer/BufferUtil.java
  rsocket-core/src/main/java/io/rsocket/buffer/Tuple2ByteBuf.java
  rsocket-core/src/main/java/io/rsocket/buffer/Tuple3ByteBuf.java
  rsocket-core/src/main/java/io/rsocket/buffer/TupleByteBuf.java
  rsocket-core/src/test/java/io/rsocket/buffer/Tuple3ByteBufTest.java
Labels: minor, refactorings

#805 Deprecate AbstractRSocket and provide alternative
  rsocket-core/src/main/java/io/rsocket/AbstractRSocket.java
  rsocket-core/src/main/java/io/rsocket/RSocket.java
  rsocket-core/src/main/java/io/rsocket/SocketAcceptor.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/channel/ChannelEchoClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/duplex/DuplexClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/lease/LeaseExample.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/requestresponse/HelloWorldClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/resume/ResumeFileTransfer.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/stream/StreamingClient.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketHeadersSample.java
  rsocket-examples/src/test/java/io/rsocket/integration/IntegrationTest.java
  rsocket-examples/src/test/java/io/rsocket/integration/InteractionsLoadTest.java
  rsocket-examples/src/test/java/io/rsocket/integration/TcpIntegrationTest.java
  rsocket-examples/src/test/java/io/rsocket/integration/TestingStreaming.java
  rsocket-examples/src/test/java/io/rsocket/resume/ResumeIntegrationTest.java
  rsocket-load-balancer/src/main/java/io/rsocket/client/LoadBalancedRSocketMono.java
  rsocket-test/src/main/java/io/rsocket/test/PingHandler.java
  rsocket-test/src/main/java/io/rsocket/test/TestRSocket.java
  rsocket-transport-netty/src/test/java/io/rsocket/integration/FragmentTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebSocketTransportIntegrationTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/WebsocketPingPongIntegrationTest.java
Labels: enhancement, new API

#806 reduces maintenance complexity
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/internal/BitUtil.java
  rsocket-core/src/main/java/io/rsocket/internal/CollectionUtil.java
  rsocket-core/src/main/java/io/rsocket/internal/Hashing.java
  rsocket-core/src/main/java/io/rsocket/internal/LimitableRequestPublisher.java
  rsocket-core/src/main/java/io/rsocket/internal/SwitchTransformFlux.java
  rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoEmpty.java
  rsocket-core/src/main/java/io/rsocket/internal/UnicastMonoProcessor.java
  rsocket-core/src/main/java/io/rsocket/util/DisposableUtils.java
  rsocket-core/src/main/java/io/rsocket/util/DuplexConnectionProxy.java
  rsocket-core/src/main/java/io/rsocket/util/Function3.java
  rsocket-core/src/main/java/io/rsocket/util/MonoLifecycleHandler.java
  rsocket-core/src/main/java/io/rsocket/util/MultiSubscriberRSocket.java
  rsocket-core/src/main/java/io/rsocket/util/OnceConsumer.java
  rsocket-core/src/main/java/io/rsocket/util/RecyclerFactory.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/internal/LimitableRequestPublisherTest.java
  rsocket-core/src/test/java/io/rsocket/internal/SwitchTransformFluxTest.java
  rsocket-core/src/test/java/io/rsocket/internal/UnicastMonoEmptyTest.java
  rsocket-core/src/test/java/io/rsocket/internal/UnicastMonoProcessorTest.java
Labels: refactorings

#808 adds missing NPE catch in order to handle rare racing cases
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
Labels: bug
