Repository rsocket/rsocket-java, pull requests merged in 2020-05, with the labels that each got.

#807 provides supportive class to hide concurrency complexity
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RequestOperator.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
Labels: refactorings

#809 provides `Payload` `refCnt` verification
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
Labels: enhancement

#811 provides ordered stream id issuing
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/test/java/io/rsocket/TestScheduler.java
  rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
Labels: bug

#813 Add Javadoc to RSocketConnector and RSocketServer
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/core/Resume.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketServerFragmentationTest.java
Labels: documentation

#814 relaxed stream id supplement
  rsocket-core/src/main/java/io/rsocket/core/StreamIdSupplier.java
Labels: enhancement

#829 removes limit rate operator
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptorExample.java
  rsocket-test/src/main/java/io/rsocket/test/TransportTest.java
Labels: enhancement

#830 provides `bindNow` shortcut for the server
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
Labels: enhancement

#832 removes deprecated errorConsumer
  rsocket-core/src/main/java/io/rsocket/RSocketFactory.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/internal/ClientServerInputMultiplexer.java
  rsocket-core/src/main/java/io/rsocket/lease/ResponderLeaseHandler.java
  rsocket-core/src/test/java/io/rsocket/core/AbstractSocketRule.java
  rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
Labels: task

#833 fixes onClose behaviour to not error on shutdown
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
Labels: bug

#834 includes LimitRateInterceptor as a built-in interceptor
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/plugins/LimitRateInterceptor.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/plugins/LimitRateInterceptorExample.java
Labels: enhancement

#824 provides support for TracingMetadata
  rsocket-core/src/main/java/io/rsocket/metadata/TracingMetadata.java
  rsocket-core/src/main/java/io/rsocket/metadata/TracingMetadataCodec.java
  rsocket-core/src/test/java/io/rsocket/metadata/TracingMetadataCodecTest.java
Labels: enhancement

#836 Apply FragmentationDuplexConnection from a single place
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/FrameFragmenter.java
  rsocket-core/src/main/java/io/rsocket/fragmentation/ReassemblyDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/transport/ClientTransport.java
  rsocket-core/src/main/java/io/rsocket/transport/ServerTransport.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationDuplexConnectionTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FragmentationIntegrationTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/FrameFragmenterTest.java
  rsocket-core/src/test/java/io/rsocket/fragmentation/ReassembleDuplexConnectionTest.java
  rsocket-core/src/test/java/io/rsocket/test/util/TestClientTransport.java
  rsocket-core/src/test/java/io/rsocket/test/util/TestServerTransport.java
  rsocket-examples/src/main/java/io/rsocket/examples/transport/ws/WebSocketHeadersSample.java
  rsocket-examples/src/test/java/io/rsocket/resume/DisconnectableClientTransport.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalServerTransport.java
  rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalClientTransportTest.java
  rsocket-transport-local/src/test/java/io/rsocket/transport/local/LocalServerTransportTest.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/client/TcpClientTransportTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/client/WebsocketClientTransportTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/TcpServerTransportTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketRouteTransportTest.java
  rsocket-transport-netty/src/test/java/io/rsocket/transport/netty/server/WebsocketServerTransportTest.java
Labels: refactorings

#840 provides well documented lease example
  rsocket-examples/src/main/java/io/rsocket/examples/transport/tcp/lease/LeaseExample.java
Labels: documentation

#843 bugfix `RSocketConnector#setupPayload` to copy the content
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketConnectorTest.java
Labels: bug

#848 ensures streams are terminated if racing terminal and new stream
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
Labels: bug

#847 fixes ReconnectMono behaviour when racing invalidate and subscribe #847
  rsocket-core/src/main/java/io/rsocket/core/ReconnectMono.java
  rsocket-core/src/test/java/io/rsocket/core/ReconnectMonoTests.java
Labels: bug

#851 Forward compatibility with Reactor Netty 1.0
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/CloseableChannel.java
Labels: task
