Repository rsocket/rsocket-java, pull requests merged in 2023-04, with the labels that each got.

#1086 ensures LoadbalancedRSocket select new rsocket upon re-subscription RC
  rsocket-core/build.gradle
  rsocket-core/src/main/java/io/rsocket/loadbalance/LoadbalanceRSocketClient.java
  rsocket-core/src/test/java/io/rsocket/loadbalance/LoadbalanceRSocketClientTest.java
Labels: bug

#1085 ensures `onClose` awaits all underlying components to be closed
  rsocket-core/src/jcstress/java/io/rsocket/resume/InMemoryResumableFramesStoreStressTest.java
  rsocket-core/src/main/java/io/rsocket/core/ClientServerInputMultiplexer.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketConnector.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketRequester.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketResponder.java
  rsocket-core/src/main/java/io/rsocket/core/RSocketServer.java
  rsocket-core/src/main/java/io/rsocket/core/ServerSetup.java
  rsocket-core/src/main/java/io/rsocket/core/SetupHandlingDuplexConnection.java
  rsocket-core/src/main/java/io/rsocket/internal/UnboundedProcessor.java
  rsocket-core/src/main/java/io/rsocket/keepalive/KeepAliveHandler.java
  rsocket-core/src/main/java/io/rsocket/resume/ClientRSocketSession.java
  rsocket-core/src/main/java/io/rsocket/resume/InMemoryResumableFramesStore.java
  rsocket-core/src/main/java/io/rsocket/resume/ResumableDuplexConnection.java
  rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
  rsocket-examples/build.gradle
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalClientTransport.java
  rsocket-transport-local/src/main/java/io/rsocket/transport/local/LocalDuplexConnection.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/TcpDuplexConnection.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/TcpClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/client/WebsocketClientTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/TcpServerTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketRouteTransport.java
  rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/server/WebsocketServerTransport.java
Labels: enhancement

#1090 improves tests & ensures thereare no leaks of bufs at execution
  rsocket-core/src/main/java/io/rsocket/core/DefaultRSocketClient.java
  rsocket-core/src/test/java/io/rsocket/core/ClientServerInputMultiplexerTest.java
  rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java
  rsocket-core/src/test/java/io/rsocket/core/KeepAliveTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketConnectorTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketLeaseTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketReconnectTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterSubscribersTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTerminationTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketRequesterTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketResponderTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketServerFragmentationTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketServerTest.java
  rsocket-core/src/test/java/io/rsocket/core/RSocketTest.java
  rsocket-core/src/test/java/io/rsocket/core/SetupRejectionTest.java
  rsocket-core/src/test/java/io/rsocket/exceptions/ExceptionsTest.java
  rsocket-core/src/test/java/io/rsocket/loadbalance/LoadbalanceRSocketClientTest.java
  rsocket-core/src/test/java/io/rsocket/loadbalance/LoadbalanceTest.java
  rsocket-core/src/test/java/io/rsocket/metadata/CompositeMetadataCodecTest.java
  rsocket-core/src/test/java/io/rsocket/metadata/MimeTypeMetadataCodecTest.java
  rsocket-core/src/test/java/io/rsocket/plugins/RequestInterceptorTest.java
  rsocket-core/src/test/java/io/rsocket/resume/ClientRSocketSessionTest.java
  rsocket-core/src/test/java/io/rsocket/resume/ServerRSocketSessionTest.java
  rsocket-core/src/test/java/io/rsocket/test/util/TestClientTransport.java
  rsocket-examples/src/test/java/io/rsocket/integration/TestingStreaming.java
Labels: task

#1091 adds class check for discarded values
  rsocket-core/src/main/java/io/rsocket/core/DefaultRSocketClient.java
  rsocket-core/src/main/java/io/rsocket/core/SendUtils.java
  rsocket-core/src/test/java/io/rsocket/core/DefaultRSocketClientTests.java
  rsocket-core/src/test/java/io/rsocket/core/SendUtilsTest.java
Labels: enhancement
